### ISSUE TITLE
Adding limitation to SignUp/SignIn flow

### ISSUE THREAD

**Issue by mdestafadilah** [massoudmaboudi/docusaurus-auth-firebase#1]
any update here?

**Comment by massoudmaboudi** [comment]
@mdestafadilah 
I am writing and finishing up the documentation. 
Hang tight and support in [hashnode.iammassoud.net](hashnode.iammassoud.net)

**Comment by mdestafadilah** [comment]
Yes!
i waiting this, thanks btw.
