### ISSUE TITLE
issue-2: yarn build failed

### ISSUE THREAD

**Issue by mdestafadilah** [massoudmaboudi/docusaurus-auth-firebase#2]
```
ReferenceError: window is not defined
[ERROR] Unable to build website for locale en.
[ERROR] Error: Failed to compile with errors.
    at D:\REACT-DEV\....\node_modules\@docusaurus\core\lib\webpack\utils.js:180:24
    at D:\REACT-DEV\....\node_modules\webpack\lib\MultiCompiler.js:554:14
    at processQueueWorker (D:\REACT-DEV\....\node_modules\webpack\lib\MultiCompiler.js:491:6)
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
```

after follow your tutorial, i have facing this problem, when i create some file in theme folder.

any clue?

**Comment by massoudmaboudi** [comment]
@mdestafadilah 
Please fetch the new changes and retry.

**Comment by mdestafadilah** [comment]
nice it's work, thanks btw bro. keep await your next tutorial. :)

**Comment by massoudmaboudi** [comment]
> nice it's work, thanks btw bro. keep await your next tutorial. :)

Check this new tutorial released today.
https://iammassoud.net/blog/protect-custom-routes-in-docusaurus-using-google-firebase
